import React, { useEffect, useState } from 'react';
import { LineChart, Line, XAxis, YAxis, ResponsiveContainer, Tooltip } from 'recharts';
import { num } from '../App.jsx';
export default function Goals({ goals, weightLog, setGoals, logWeight }) {
  const [g,setG] = useState(goals); useEffect(()=>setG(goals),[goals]);
  const start=num(g.startWeight), current=num(g.currentWeight), target=num(g.targetWeight); const losing=start>target; const total=Math.abs(start-target)||1; const done= losing ? Math.max(0,start-current) : Math.max(0,current-start); const pct = start&&target?Math.min(100,Math.round(done/total*100)):0;
  const daysLeft = g.targetDate ? Math.max(0, Math.ceil((new Date(g.targetDate)-new Date())/86400000)) : null;
  const chart = weightLog.map(w=>({date:w.date.slice(5), peso:w.weight}));
  function save(){ setGoals(g); if(g.currentWeight) logWeight(g.currentWeight); }
  return <><section className="card"><h2>Il tuo obiettivo</h2><div className="grid2"><input type="number" step="0.1" placeholder="Peso iniziale kg" value={g.startWeight} onChange={e=>setG({...g,startWeight:e.target.value})}/><input type="number" step="0.1" placeholder="Peso attuale kg" value={g.currentWeight} onChange={e=>setG({...g,currentWeight:e.target.value})}/><input type="number" step="0.1" placeholder="Peso obiettivo kg" value={g.targetWeight} onChange={e=>setG({...g,targetWeight:e.target.value})}/><input type="date" value={g.targetDate} onChange={e=>setG({...g,targetDate:e.target.value})}/><input type="number" placeholder="Kcal giornaliere" value={g.dailyKcal} onChange={e=>setG({...g,dailyKcal:e.target.value})}/><input type="number" placeholder="Carboidrati g" value={g.carbsGoal} onChange={e=>setG({...g,carbsGoal:e.target.value})}/><input type="number" placeholder="Proteine g" value={g.proteinGoal} onChange={e=>setG({...g,proteinGoal:e.target.value})}/><input type="number" placeholder="Grassi g" value={g.fatGoal} onChange={e=>setG({...g,fatGoal:e.target.value})}/></div><button onClick={save}>Salva obiettivi</button></section>{start>0&&target>0&&<section className="card"><h2>Avanzamento</h2><div className="macro"><div className="macro-head"><span>Progresso</span><b>{pct}%</b></div><div className="progress"><span style={{width:`${pct}%`}}/></div></div>{daysLeft!==null&&<p className="hint">Giorni rimanenti: {daysLeft}</p>}</section>}{chart.length>1&&<section className="card"><h2>Storico peso</h2><div className="chart"><ResponsiveContainer width="100%" height={220}><LineChart data={chart}><XAxis dataKey="date"/><YAxis domain={['dataMin - 1','dataMax + 1']}/><Tooltip/><Line type="monotone" dataKey="peso" stroke="#16a34a" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section>}</>;
}
