import React, { useState } from 'react';
import { Trash2 } from 'lucide-react';
import { uid, num } from '../App.jsx';
const emptyMeal = { name:'', time:'', description:'', kcal:'', carbs:'', protein:'', fat:'' };
export default function MealPlan({ mealPlan, updatePlan, onLogMeal }) {
  const [plan,setPlan] = useState(mealPlan || {pdfName:'',dailyKcalTarget:'',notes:'',meals:[]});
  const [meal,setMeal] = useState(emptyMeal);
  function commit(next){ setPlan(next); updatePlan(next); }
  function addPlannedMeal(){ if(!meal.name.trim()) return; commit({...plan, meals:[...(plan.meals||[]), {id:uid(), ...meal, kcal:num(meal.kcal), carbs:num(meal.carbs), protein:num(meal.protein), fat:num(meal.fat)}]}); setMeal(emptyMeal); }
  function remove(id){ commit({...plan, meals: plan.meals.filter(m=>m.id!==id)}); }
  return <><section className="card"><h2>Piano alimentare</h2><p className="hint">Versione locale fase 5: puoi caricare il PDF come riferimento e trascrivere i pasti previsti. L'estrazione automatica tramite AI verrà aggiunta in seguito.</p><label className="file-btn full">Carica PDF piano alimentare<input hidden type="file" accept="application/pdf" onChange={e=>{const f=e.target.files?.[0]; if(f) commit({...plan,pdfName:f.name});}}/></label>{plan.pdfName&&<p className="hint">PDF selezionato: {plan.pdfName}</p>}<div className="grid2"><input type="number" placeholder="Target kcal giornaliere" value={plan.dailyKcalTarget||''} onChange={e=>commit({...plan,dailyKcalTarget:e.target.value})}/><textarea placeholder="Note generali del piano" value={plan.notes||''} onChange={e=>commit({...plan,notes:e.target.value})}/></div></section><section className="card"><h2>Aggiungi pasto previsto</h2><div className="grid2"><input placeholder="Nome pasto, es. Colazione" value={meal.name} onChange={e=>setMeal({...meal,name:e.target.value})}/><input placeholder="Orario/momento" value={meal.time} onChange={e=>setMeal({...meal,time:e.target.value})}/><textarea placeholder="Descrizione alimenti" value={meal.description} onChange={e=>setMeal({...meal,description:e.target.value})}/><input type="number" placeholder="Kcal" value={meal.kcal} onChange={e=>setMeal({...meal,kcal:e.target.value})}/><input type="number" placeholder="Carboidrati g" value={meal.carbs} onChange={e=>setMeal({...meal,carbs:e.target.value})}/><input type="number" placeholder="Proteine g" value={meal.protein} onChange={e=>setMeal({...meal,protein:e.target.value})}/><input type="number" placeholder="Grassi g" value={meal.fat} onChange={e=>setMeal({...meal,fat:e.target.value})}/></div><button onClick={addPlannedMeal}>Aggiungi al piano</button></section><section className="card"><h2>Pasti previsti</h2>{(!plan.meals||plan.meals.length===0)&&<p className="empty">Nessun pasto previsto inserito.</p>}{plan.meals?.map(m=><div className="planned" key={m.id}><div><b>{m.name}</b>{m.time&&<span className="pill">{m.time}</span>}<p>{m.description}</p><p>C {m.carbs}g · P {m.protein}g · G {m.fat}g</p></div><strong>{m.kcal} kcal</strong><div className="planned-actions"><button onClick={()=>onLogMeal({name:m.name,kcal:m.kcal,carbs:m.carbs,protein:m.protein,fat:m.fat,source:'piano'})}>Segna mangiato oggi</button><button className="ghost danger" onClick={()=>remove(m.id)}><Trash2 size={16}/></button></div></div>)}</section></>;
}
